name: "Documentation"
on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Install and Build
      - uses: actions/checkout@v2
      - uses: sphinx-toolbox/sphinx-action@master
        with:
          pre-build-command: "pip install -r requirements.txt"
          docs-folder: "docs/"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html
